### ISSUE TITLE
docker compose启动servicecomb-kie报错

### ISSUE THREAD

**Issue by hityc2019** [apache/servicecomb-kie#148]
使用命令docker-compose up启动kie时报错，
命令：
```
cd servicecomb-kie/deployments/docker
sudo docker-compose up
```
部分日志如下：
```
mongo-express_1    | /node_modules/mongodb/lib/server.js:265
mongo-express_1    |         process.nextTick(function() { throw err; })
mongo-express_1    |                                       ^
mongo-express_1    | MongoError: failed to connect to server [mongo:27017] on first connect
mongo-express_1    |     at Pool.<anonymous> (/node_modules/mongodb-core/lib/topologies/server.js:326:35)
mongo-express_1    |     at emitOne (events.js:116:13)
mongo-express_1    |     at Pool.emit (events.js:211:7)
mongo-express_1    |     at Connection.<anonymous> (/node_modules/mongodb-core/lib/connection/pool.js:270:12)
mongo-express_1    |     at Object.onceWrapper (events.js:317:30)
mongo-express_1    |     at emitTwo (events.js:126:13)
mongo-express_1    |     at Connection.emit (events.js:214:7)
mongo-express_1    |     at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:175:49)
mongo-express_1    |     at Object.onceWrapper (events.js:315:30)
mongo-express_1    |     at emitOne (events.js:116:13)
docker_mongo-express_1 exited with code 1
mongo-express_1    | /docker-entrypoint.sh: line 14: mongo: Try again
mongo-express_1    | /docker-entrypoint.sh: line 14: /dev/tcp/mongo/27017: Invalid argument
mongo-express_1    | Mon Jul 20 02:54:58 UTC 2020 retrying to connect to mongo:27017 (2/5)
mongo-express_1    | /docker-entrypoint.sh: line 14: mongo: Try again
mongo-express_1    | /docker-entrypoint.sh: line 14: /dev/tcp/mongo/27017: Invalid argument
mongo-express_1    | Mon Jul 20 02:55:04 UTC 2020 retrying to connect to mongo:27017 (3/5)
mongo-express_1    | /docker-entrypoint.sh: line 14: mongo: Try again
mongo-express_1    | /docker-entrypoint.sh: line 14: /dev/tcp/mongo/27017: Invalid argument
mongo-express_1    | Mon Jul 20 02:55:10 UTC 2020 retrying to connect to mongo:27017 (4/5)
mongo-express_1    | /docker-entrypoint.sh: line 14: mongo: Try again
mongo-express_1    | /docker-entrypoint.sh: line 14: /dev/tcp/mongo/27017: Invalid argument
mongo-express_1    | Mon Jul 20 02:55:16 UTC 2020 retrying to connect to mongo:27017 (5/5)
```

**Comment by hityc2019** [comment]
需要更新最新镜像

**Comment by tianxiaoliang** [comment]
@hityc2019 是否需要修复什么，还是我们push最新镜像到dockerhub

**Comment by hityc2019** [comment]
不需要，只是这个文档http://servicecomb.apache.org/docs/kie/0.1.0/index.html地址需要更新成latest，里面的一些接口已经更改，容易误导用户

**Comment by hityc2019** [comment]
官网文档 | 0.1.0 http://servicecomb.apache.org/docs/kie/0.1.0/index.html
-- | --
github网站 | Latest   https://kie.readthedocs.io/en/latest/
deployments/docker目录 | latest
examples/dev目录 | latest

Apache官网文档是按照版本发布的，但是0.1.0版本的api和github社区最新分支差别很大，因此可能使用户混淆使用

目前的方案如下：
更改 deployments/docker目录下的镜像版本为0.1.0版本

examples/dev目录在readme中详细说明官网文档（跟随版本发布）和最新sphinx文档（latest）有差别
