### ISSUE TITLE
使用Quick start方式，mongoDB和mongo-express均正常启动，但是servicecomb-kie启动失败

### ISSUE THREAD

**Issue by TangLeDaily** [apache/servicecomb-kie#292]
尝试过Linux版本：
- ubuntu 22、20
mongoDB版本：
- 6.0.8
报错信息：
`servicecomb-kie_1  | panic: 2023-08-01 08:00:58.779 +00:00 FATAL mongo/mongo.go:237 failed to create collection with validation
servicecomb-kie_1  | 
servicecomb-kie_1  | goroutine 1 [running]:
servicecomb-kie_1  | github.com/go-chassis/seclog/third_party/forked/cloudfoundry/lager.(*logger).logs(0xc000300540, {0x203000?, 0xc000195500?, 0x0?}, 0x4, {0x1611c05, 0x2b}, {0x0, 0x0, 0x0})
servicecomb-kie_1  | 	/opt/prj/go/servicecomb-kie/vendor/github.com/go-chassis/seclog/third_party/forked/cloudfoundry/lager/logger.go:189 +0x4a5
servicecomb-kie_1  | github.com/go-chassis/seclog/third_party/forked/cloudfoundry/lager.(*logger).log(0xc000300540, 0x4, {0x1611c05, 0x2b}, {0x0, 0x0, 0x0})
servicecomb-kie_1  | 	/opt/prj/go/servicecomb-kie/vendor/github.com/go-chassis/seclog/third_party/forked/cloudfoundry/lager/logger.go:136 +0xe6
servicecomb-kie_1  | github.com/go-chassis/seclog/third_party/forked/cloudfoundry/lager.(*logger).Fatal(0x60?, {0x1611c05?, 0xc000195500?}, {0x0?, 0x0?, 0x7f2e732b86c0?})
servicecomb-kie_1  | 	/opt/prj/go/servicecomb-kie/vendor/github.com/go-chassis/seclog/third_party/forked/cloudfoundry/lager/logger.go:210 +0x37
servicecomb-kie_1  | github.com/go-chassis/cari/db/mongo.wrapCreateCollectionError({0x190f1a0?, 0xc0004cca50?})
servicecomb-kie_1  | 	/opt/prj/go/servicecomb-kie/vendor/github.com/go-chassis/cari/db/mongo/mongo.go:237 +0x15c
servicecomb-kie_1  | github.com/go-chassis/cari/db/mongo.EnsureCollection({0x15d0710, 0x7}, {0x141af20?, 0xc0003a5980?}, {0xc00063fcb0, 0x1, 0x1})
servicecomb-kie_1  | 	/opt/prj/go/servicecomb-kie/vendor/github.com/go-chassis/cari/db/mongo/mongo.go:225 +0xea
servicecomb-kie_1  | github.com/apache/servicecomb-kie/server/datasource/mongo.ensureRevisionCounter()
servicecomb-kie_1  | 	/opt/prj/go/servicecomb-kie/server/datasource/mongo/init.go:85 +0x29c
servicecomb-kie_1  | github.com/apache/servicecomb-kie/server/datasource/mongo.ensureDB()
servicecomb-kie_1  | 	/opt/prj/go/servicecomb-kie/server/datasource/mongo/init.go:67 +0x19
servicecomb-kie_1  | github.com/apache/servicecomb-kie/server/datasource/mongo.NewFrom(0x13f1180?)
servicecomb-kie_1  | 	/opt/prj/go/servicecomb-kie/server/datasource/mongo/init.go:44 +0x17
servicecomb-kie_1  | github.com/apache/servicecomb-kie/server/datasource.Init({0xc0003b2558, 0x5})
servicecomb-kie_1  | 	/opt/prj/go/servicecomb-kie/server/datasource/dao.go:127 +0x55
servicecomb-kie_1  | github.com/apache/servicecomb-kie/server.Run()
servicecomb-kie_1  | 	/opt/prj/go/servicecomb-kie/server/server.go:46 +0x1c8
servicecomb-kie_1  | main.main()
servicecomb-kie_1  | 	/opt/prj/go/servicecomb-kie/cmd/kieserver/main.go:54 +0x4d`

**Comment by jianghuSPR** [comment]
Has this problem been solved? I am anxious to know the solution to this problem.

**Comment by mniwjb** [comment]
The reason of this problem has be found, see another issue: #244

**Comment by mniwjb** [comment]
The reason of this problem has be found, see another issue: #244

**Comment by mniwjb** [comment]
> Has this problem been solved? I am anxious to know the solution to this problem.

#244
